default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['KORONA_DATABASE_NAME'] %>

test:
  <<: *default
  database: <%= ENV['KORONA_DATABASE_NAME'] %>

production:
  <<: *default
  database: korona_kapital_production
  username: deploy
  password: Rails.application.credentials.dig(:production, :db_password)

